name: Data Pipeline CI/CD Quality Gate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  quality-assurance:
    name: Lint, Test, and Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Codebase
        uses: actions/checkout@v4

      - name: Set up Python Environment (3.12)
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Set up Java Runtime Environment (OpenJDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Linting and Testing Suites
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black pytest pyspark psycopg2-binary boddle

      - name: Enforce Code Formatting (Black)
        run: |
          black --check src/ tests/

      - name: Enforce Code Quality and Structural Integrity (Flake8)
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 src/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. Max-line-length matching default PEP8 profiles.
          flake8 src/ tests/ --count --max-line-length=127 --statistics

      - name: Execute PySpark Pipeline Test Matrices
        run: |
          pytest tests/
  
  deploy:
    name: Deploy Artifacts to AWS S3
    needs: [quality-assurance]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Deploy Scripts to S3 Data Lake
        run: |
          aws s3 sync src/jobs/ s3://${{ vars.S3_CODE_BUCKET }}/jobs/ --delete

      - name: Deploy Cloud Orchestration to Airflow DAGs
        run: |
          aws s3 sync airflow/dags/ s3://${{ vars.S3_AIRFLOW_DAGS_BUCKET }}/dags/ --delete